Algoritmo "LO5A"
// Disciplina   : [Lógica de Programação com Javascript]
// Professor   : Jailson 
// Descrição   : O algoritmo mostra o quadrado dos numeros inteiros de 15 ate 200
// Autor(a)    : Isabelle Victoria Pereira
// Data atual  : 29/05/2022
Var
// Seção de Declarações das variáveis 
contadora: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
para contadora de 15 ate 200 passo 1 faca
escreval(contadora^2)
fimpara

Fimalgoritmo