Algoritmo "LO5C"
// Disciplina   : [Lógica de Programação com Javascript]
// Professor   : Jailson 
// Descrição   : Apresenta a soma dos números 1 até 100
// Autor(a)    : Isabelle Victoria Pereira
// Data atual  : 29/05/2022

Var
// Seção de Declarações das variáveis 
contadora,acomuladora: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para contadora de 1 ate 100 passo 1 faca
acomuladora<- acomuladora+contadora
escreval(acomuladora)
fimpara

Fimalgoritmo