Algoritmo "LO5D"
// Disciplina   : [Lógica de Programação com Javascript]
// Professor   : Jailson 
// Descrição   : Soma dos números pares de 1 a 500
// Autor(a)    : Isabelle Victoria Pereira
// Data atual  : 29/05/2022

Var
// Seção de Declarações das variáveis 
contadora,acomuladora: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para contadora de 2 ate 500 passo 2 faca
acomuladora<- acomuladora+contadora
fimpara
escreval(acomuladora)
Fimalgoritmo